### PR TITLE
fix `starknet_getEvents` returning wildcard error on nonexistent block

### LINKED ISSUE #498: `starknet_getEvents` returning wildcard error on nonexistent block
**Describe the bug (observed vs expected behavior)**
version 0.0.7 with flag `--state-archive-capacity full`
when passing not existing block number got an [WILDCARD_RPC_ERROR_CODE](https://github.com/0xSpaceShard/starknet-devnet-rs/blob/3ad81456092a2da939be1f590855cea2c18ce40c/crates/starknet-devnet-server/src/api/json_rpc/mod.rs#L56) .
```
POST /rpc HTTP/1.1
user-agent: Dart/3.4 (dart:io)
content-type: application/json; charset=utf-8
accept-encoding: gzip
content-length: 149
host: 0.0.0.0:5050

{"jsonrpc": "2.0", "method": "starknet_getEvents", "params": [{"from_block": {"block_number": 100}, "to_block": "latest", "chunk_size": 0}], "id": 0}HTTP/1.1 200 OK
content-type: application/json
content-length: 71
vary: origin, access-control-request-method, access-control-request-headers
access-control-allow-origin: *
date: Mon, 17 Jun 2024 14:56:50 GMT

{"jsonrpc":"2.0","id":0,"error":{"code":-1,"message":"No block found"}}
```

should return [BLOCK_NOT_FOUND](https://github.com/starkware-libs/starknet-specs/blob/8016dd08ed7cd220168db16f24c8a6827ab88317/api/starknet_api_openrpc.json#L633)

### PR DESCRIPTION
**Pull request by tonypony220**
## Usage related changes
fix #498 

## Checklist:

- [x] Checked out the [contribution guidelines](CONTRIBUTING.md)
- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/clippy_check.sh`
- [x] No unused dependencies - `./scripts/check_unused_deps.sh`
- [x] No spelling errors - `./scripts/check_spelling.sh`
- [x] Performed code self-review
- [x] Rebased to the latest commit of the target branch (or merged it into my branch)
- [x] Updated the docs if needed - `./website/README.md`
- [x] Linked the [issues](https://github.com/0xSpaceShard/starknet-devnet-rs/issues) resolvable by this PR - [linking info](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [x] Updated the tests if needed; all passing - [execution info](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#test-execution)

### CODE REVIEW

File: crates/starknet-devnet-server/src/api/json_rpc/endpoints.rs [hunk 1]
```diff
@@ -376,14 +376,19 @@ impl JsonRpcHandler {
...
+            .get_events(
+                filter.from_block,
+                filter.to_block,
+                filter.address,
+                filter.keys,
+                page * filter.chunk_size,
+                Some(filter.chunk_size),
+            )
+            .map_err(|err| match err {
+                Error::NoBlock => ApiError::BlockNotFound,
```
Comment (FabijanC) [inline crates/starknet-devnet-server/src/api/json_rpc/endpoints.rs:389]: Why not do this error mapping in the same place as other json-rpc method implementations?

File: crates/starknet-devnet/tests/test_get_events.rs [hunk 2]
```diff
@@ -151,4 +151,44 @@ mod get_events_integration_tests {
...
+        };
+        match devnet
+            .json_rpc_client
+            .get_events(event_filter.clone(), continuation_token.clone(), chunk_size as u64)
+            .await
+            .unwrap_err()
+        {
+            ProviderError::StarknetError(StarknetError::BlockNotFound) => (),
+            err => panic!("Invalid error: {err:?}"),
+        }
```
Comment (FabijanC) [inline crates/starknet-devnet/tests/test_get_events.rs:175]: We can save one line here and in the other such occurrence:
```suggestion
            .await
        {
            Err(ProviderError::StarknetError(StarknetError::BlockNotFound)) => (),
            resp => panic!("Unexpected response: {resp:?}"),
        }
```

File: crates/starknet-devnet/tests/test_get_events.rs [hunk 3]
```diff
@@ -151,4 +151,44 @@ mod get_events_integration_tests {
 
         get_events_correct_chunking(&devnet, true).await
     }
+
+    #[tokio::test]
+    async fn get_events_errors() {
+        let devnet = BackgroundDevnet::spawn().await.expect("Could not start Devnet");
+
+        let chunk_size = 3;
```
Comment (FabijanC) [inline crates/starknet-devnet/tests/test_get_events.rs:159]: Instead of casting below, why not define the correct type right away:
```suggestion
        let chunk_size = 3_u64;
```

File: crates/starknet-devnet/tests/test_get_events.rs [hunk 4]
```diff
@@ -151,4 +151,44 @@ mod get_events_integration_tests {
...
+        continuation_token = Some(String::from("invalid token"));
+        let event_filter = EventFilter {
+            from_block: Some(BlockId::Number(0)),
+            to_block: Some(BlockId::Tag(BlockTag::Latest)),
+            address: None,
+            keys: None,
+        };
+        match devnet
+            .json_rpc_client
+            .get_events(event_filter.clone(), continuation_token.clone(), chunk_size as u64)
```
Comment (FabijanC) [inline crates/starknet-devnet/tests/test_get_events.rs:186]: Is `clone` necessary here? The variables are not used after this line anymore. But in fact, instead of redefining variables or making them mutable, why not just use two blocks with their own namespaces? E.g. L177-L193 could be put inside of curly braces.

File: crates/starknet-devnet/tests/test_get_events.rs [hunk 5]
```diff
@@ -151,4 +151,44 @@ mod get_events_integration_tests {
...
+            .await
+            .unwrap_err()
+        {
+            ProviderError::StarknetError(StarknetError::BlockNotFound) => (),
+            err => panic!("Invalid error: {err:?}"),
+        }
+
+        continuation_token = Some(String::from("invalid token"));
```
Comment (FabijanC) [inline crates/starknet-devnet/tests/test_get_events.rs:177]: Why is `continuation_token` mutable, but `event_filter` is simply redefined?

**Review by FabijanC — CHANGES_REQUESTED** [review]

File: crates/starknet-devnet-server/src/api/json_rpc/endpoints.rs (hunk 1 above)
Comment (tonypony220) [reply crates/starknet-devnet-server/src/api/json_rpc/endpoints.rs:389]: From what I can see, internal errors map to API errors in this layer (endpoints.rs). Could you please clarify your question?

File: crates/starknet-devnet-core/src/messaging/ethereum.rs [hunk 6]
```diff
@@ -219,7 +219,8 @@ impl EthereumMessaging {
                 Some(receipt) => {
                     trace!(
                         "Message {:064x} sent on L1 with transaction hash {:#x}",
-                        message_hash, receipt.transaction_hash,
+                        message_hash,
+                        receipt.transaction_hash,
```
[the remark this answers is not in the document]
Comment (tonypony220) [reply crates/starknet-devnet-core/src/messaging/ethereum.rs:223]: Okay! Do you know why it needs to be reinstalled? It doesn't format correctly after just `rustup update nightly`

File: crates/starknet-devnet/tests/test_get_events.rs (hunk 4 above)
Comment (tonypony220) [reply crates/starknet-devnet/tests/test_get_events.rs:186]: you right, it would be much more clear

File: crates/starknet-devnet/tests/test_get_events.rs (hunk 3 above)
Comment (tonypony220) [reply crates/starknet-devnet/tests/test_get_events.rs:159]: my bad

File: crates/starknet-devnet/tests/test_get_events.rs (hunk 2 above)
Comment (tonypony220) [reply crates/starknet-devnet/tests/test_get_events.rs]: good point!

File: crates/starknet-devnet-core/src/messaging/ethereum.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (FabijanC) [reply crates/starknet-devnet-core/src/messaging/ethereum.rs]: Just updating could be enough, did you try it? In any case, in CI we use the nightly toolchain for formatting, that's why our local versions may not be up-to-date (I'm aware of such workflow being problematic, I'm surprised this hasn't showed up earlier).

File: crates/starknet-devnet-server/src/api/json_rpc/endpoints.rs (hunk 1 above)
Comment (FabijanC) [reply crates/starknet-devnet-server/src/api/json_rpc/endpoints.rs:389]: You're right, I don't know what I was thinking. Perhaps I was just confused by the wildcard match, but now that I've inspected the error types, it really seems like another way to do it. Resolving this.

File: crates/starknet-devnet-core/src/messaging/ethereum.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (tonypony220) [reply crates/starknet-devnet-core/src/messaging/ethereum.rs]: yes, it worked with re-installation of nightly, but did not with just update, so that's why im asking about this behavior of rustup

**Review by FabijanC — APPROVED** [review]
